#pragma once

#include "native/types.hpp"

NativeTypeMap NativeTypes {
	{     NTYPE_UNKNOWN, {  NTYPE_UNKNOWN, false, "UnknownType"}},
	{        NTYPE_VOID, {     NTYPE_VOID, false, "void"       }},
	{         NTYPE_INT, {     NTYPE_VOID, false, "int"        }},
	{      NTYPE_INTPTR, {     NTYPE_VOID,  true, "int*"       }},
	{       NTYPE_FLOAT, {     NTYPE_VOID, false, "float"      }},
	{    NTYPE_FLOATPTR, {     NTYPE_VOID,  true, "float*"     }},
	{        NTYPE_BOOL, {     NTYPE_VOID, false, "BOOL"       }},
	{     NTYPE_BOOLPTR, {     NTYPE_VOID,  true, "BOOL*"      }},
	{     NTYPE_CHARPTR, {     NTYPE_VOID,  true, "char*"      }},
	{      NTYPE_STRING, {     NTYPE_VOID,  true, "const char*"}},
	{         NTYPE_ANY, {     NTYPE_VOID, false, "Any"        }},
	{      NTYPE_ANYPTR, {     NTYPE_VOID,  true, "Any*"       }},
	{        NTYPE_BLIP, {     NTYPE_VOID, false, "Blip"       }},
	{     NTYPE_BLIPPTR, {     NTYPE_VOID,  true, "Blip*"      }},
	{         NTYPE_CAM, {     NTYPE_VOID, false, "Cam"        }},
	{      NTYPE_CAMPTR, {     NTYPE_VOID,  true, "Cam*"       }},
	{      NTYPE_ENTITY, {     NTYPE_VOID, false, "Entity"     }},
	{   NTYPE_ENTITYPTR, {     NTYPE_VOID,  true, "Entity*"    }},
	{      NTYPE_FIREID, {     NTYPE_VOID, false, "FireId"     }},
	{   NTYPE_FIREIDPTR, {     NTYPE_VOID,  true, "FireId*"    }},
	{        NTYPE_HASH, {     NTYPE_VOID, false, "Hash"       }},
	{     NTYPE_HASHPTR, {     NTYPE_VOID,  true, "Hash*"      }},
	{    NTYPE_INTERIOR, {     NTYPE_VOID, false, "Interior"   }},
	{ NTYPE_INTERIORPTR, {     NTYPE_VOID,  true, "Interior*"  }},
	{     NTYPE_ITEMSET, {     NTYPE_VOID, false, "ItemSet"    }},
	{  NTYPE_ITEMSETPTR, {     NTYPE_VOID,  true, "ItemSet*"   }},
	{      NTYPE_OBJECT, {   NTYPE_ENTITY, false, "Object"     }},
	{   NTYPE_OBJECTPTR, {NTYPE_ENTITYPTR,  true, "Object*"    }},
	{         NTYPE_PED, {   NTYPE_ENTITY, false, "Ped"        }},
	{      NTYPE_PEDPTR, {NTYPE_ENTITYPTR,  true, "Ped*"       }},
	{      NTYPE_PICKUP, {     NTYPE_VOID, false, "Pickup"     }},
	{   NTYPE_PICKUPPTR, {     NTYPE_VOID,  true, "Pickup*"    }},
	{      NTYPE_PLAYER, {     NTYPE_VOID, false, "Player"     }},
	{   NTYPE_PLAYERPTR, {     NTYPE_VOID,  true, "Player*"    }},
	{   NTYPE_SCRHANDLE, {     NTYPE_VOID, false, "ScrHandle"  }},
	{NTYPE_SCRHANDLEPTR, {     NTYPE_VOID,  true, "ScrHandle*" }},
	{     NTYPE_VECTOR3, {     NTYPE_VOID, false, "Vector3"    }},
	{  NTYPE_VECTOR3PTR, {     NTYPE_VOID,  true, "Vector3*"   }},
	{     NTYPE_VEHICLE, {   NTYPE_ENTITY, false, "Vehicle"    }},
	{  NTYPE_VEHICLEPTR, {NTYPE_ENTITYPTR,  true, "Vehicle*"   }},
	{   NTYPE_ANIMSCENE, {     NTYPE_VOID, false, "AnimScene"  }},
	{NTYPE_ANIMSCENEPTR, {     NTYPE_VOID,  true, "AnimScene*" }},
	{    NTYPE_PERSCHAR, {     NTYPE_VOID, false, "PersChar"   }},
	{ NTYPE_PERSCHARPTR, {     NTYPE_VOID,  true, "PersChar*"  }},
	{     NTYPE_POPZONE, {     NTYPE_VOID, false, "PopZone"    }},
	{  NTYPE_POPZONEPTR, {     NTYPE_VOID,  true, "PopZone*"   }},
	{      NTYPE_PROMPT, {     NTYPE_VOID, false, "Prompt"     }},
	{   NTYPE_PROMPTPTR, {     NTYPE_VOID,  true, "Prompt*"    }},
	{     NTYPE_PROPSET, {     NTYPE_VOID, false, "PropSet"    }},
	{  NTYPE_PROPSETPTR, {     NTYPE_VOID,  true, "PropSet*"   }},
	{      NTYPE_VOLUME, {     NTYPE_VOID, false, "Volume"     }},
	{   NTYPE_VOLUMEPTR, {     NTYPE_VOID,  true, "Volume*"    }}
};
