name: build asi

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: RedLua
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get previous tag
        id: prevtag
        shell: bash
        run: |
          echo "tag=$(GIT.EXE describe --abbrev=0 --tags ${{ github.ref_name }}^)" >> $GITHUB_OUTPUT

      - name: Checkout LuaJIT
        uses: actions/checkout@v3
        with:
          path: .\src\thirdparty\LuaJIT
          repository: LuaJIT/LuaJIT
          fetch-depth: 0

      - name: Download ScriptHookSDK
        shell: pwsh
        run: |
          .\misc\ScriptHook.ps1
          .\misc\ScriptHook.ps1 gtav

      - name: Detect MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86_64

      - name: Build plugin
        run: |
          .\build.bat nodebug
          .\build.bat gtav nodebug

      - name: Build release archive
        shell: pwsh
        run: .\misc\Pack.ps1 ${{ github.ref_name }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: Pre-release ${{ github.ref_name }}
          body: "**Full Changelog**: https://github.com/${{ github.repository }}/compare/${{ steps.prevtag.outputs.tag }}...${{ github.ref_name }}"
          files: |
            ./objs/RedLuaRDR2-${{ github.ref_name }}.zip
            ./objs/RedLuaV-${{ github.ref_name }}.zip

